import { AppointmentType } from '@/types/appointments'

export const appointmentTypes: AppointmentType[] = [
  {
    id: 'checkup',
    name: 'Regular Check-up',
    color: 'bg-blue-500',
    duration: 30,
    defaultPrice: 50,
    requiredResources: ['exam-room'],
    description: 'Routine health examination and consultation',
  },
  {
    id: 'vaccination',
    name: 'Vaccination',
    color: 'bg-green-500',
    duration: 15,
    defaultPrice: 35,
    requiredResources: ['exam-room'],
    description: 'Routine vaccinations and boosters',
  },
  {
    id: 'surgery',
    name: 'Surgery',
    color: 'bg-red-500',
    duration: 120,
    defaultPrice: 300,
    requiredResources: ['surgery-room', 'anesthesia-machine'],
    description: 'Surgical procedure',
    preparationInstructions: 'No food 12 hours before surgery',
  },
  {
    id: 'emergency',
    name: 'Emergency',
    color: 'bg-orange-500',
    duration: 60,
    defaultPrice: 150,
    requiredResources: ['emergency-room'],
    description: 'Urgent care and emergency services',
  },
  {
    id: 'grooming',
    name: 'Grooming',
    color: 'bg-purple-500',
    duration: 60,
    defaultPrice: 75,
    requiredResources: ['grooming-station'],
    description: 'Full grooming service',
  },
  {
    id: 'dental',
    name: 'Dental Cleaning',
    color: 'bg-cyan-500',
    duration: 120,
    defaultPrice: 200,
    requiredResources: ['dental-station'],
    description: 'Complete dental cleaning and examination',
  },
  {
    id: 'lab',
    name: 'Lab Work',
    color: 'bg-yellow-500',
    duration: 30,
    defaultPrice: 85,
    requiredResources: ['lab-room'],
    description: 'Laboratory tests and diagnostics',
  },
  {
    id: 'xray',
    name: 'X-Ray/Imaging',
    color: 'bg-pink-500',
    duration: 45,
    defaultPrice: 150,
    requiredResources: ['imaging-room', 'x-ray-machine'],
    description: 'Radiographic imaging services',
  },
]